### ISSUE TITLE
Context menu for "surround with Concordion command"

### ISSUE THREAD

**Issue by nigelcharman** [concordion/idea-concordion-support#10]
In order for users to know that the feature exists, and to see what keyboard shortcut it is mapped to, it would be great to add the "surround with Concordion command" feature to the context menu.

**Comment by gmandnepr** [comment]
Action converted to intention. Now it is present in alt+enter menu in both html and md concordion specs. Simple example and feature toggle is present in idea intention settings

![intentiondescription](https://cloud.githubusercontent.com/assets/1331856/14580692/2c48b7dc-03de-11e6-88ee-efb211fff06b.png)
![intentionexample](https://cloud.githubusercontent.com/assets/1331856/14580693/2c4a1a00-03de-11e6-8395-db6fc2f5f7a6.png)
