### ISSUE TITLE
Add setting for command style

### ISSUE THREAD

**Issue by nigelcharman** [concordion/idea-concordion-support#11]
Currently the plugin includes both the camel cased and spinal cased variants of commands. For example `c:assertEquals` or `c:assert-equals`:

![image](https://cloud.githubusercontent.com/assets/144202/14584825/08b4576e-04af-11e6-8901-8c2d7db958c3.png)

This makes the list longer, with more to read and select from.

I suggest we add a setting to choose either camel or spinal case, then only show the commands in that case. The default should be spinal-case, since camel case is not strictly valid XHTML.

**Comment by gmandnepr** [comment]
Configuration of concordion command case added to **Settings > Languages % Frameworkds > Concordion**

![screenshot at 2016-05-02 10 19 12](https://cloud.githubusercontent.com/assets/1331856/14949352/ebc8e9d6-1051-11e6-897f-2a4444f28338.png)

Completion will contain only configured case

![screenshot at 2016-05-02 10 19 54](https://cloud.githubusercontent.com/assets/1331856/14949351/ebc8e7c4-1051-11e6-905f-4cb56805aa62.png)

Inspection added to report usages of wrong command case

![screenshot at 2016-05-02 10 35 40](https://cloud.githubusercontent.com/assets/1331856/14949353/ebca1bb2-1051-11e6-86be-99134a37c241.png)

Quick fix is introduced

![screenshot at 2016-05-02 10 19 32](https://cloud.githubusercontent.com/assets/1331856/14949350/ebc8980a-1051-11e6-84e3-86ac063b7cb2.png)
