### ISSUE TITLE
Example name containing whitespaces causes multiple icons to appear

### ISSUE THREAD

**Issue by gdubya** [concordion/idea-concordion-support#15]
If we add whitespaces to the example name then multiple copies of the concordion icon appear in the gutter (see screenshot: 4 words, 4 icons).
![concordion-plugin](https://user-images.githubusercontent.com/446033/30882658-f53ccfcc-a309-11e7-956f-831699bb50b3.png)

**Comment by gmandnepr** [comment]
Hello,

Sorry at the moment I do not have much time now, but I will try to take a look or chat back about this nearest time.

**Comment by vgheo** [comment]
This is really annoying as it takes a lot of screen space.

Can you please at least provide an option to disable this feature ?

**Comment by vgheo** [comment]
Additionally, the same occurs on FullOGNL like
`[xxx](- "#aaa=mmm(#TEXT,{a,b,c,d}")`

**Comment by gmandnepr** [comment]
Could you please check if this build improves the situation: https://www.dropbox.com/s/8a7gxpynqn7rytf/idea-concordion-support-0.12.0-issue-15-SNAPSHOT.jar?dl=0

**Comment by gmandnepr** [comment]
No feedback received, existing fix released as part of 0.12

**Comment by gdubya** [comment]
Apologies for forgetting to give you some feedback on the snapshot. I can confirm that the issue appears to be fixed in 0.12. Thank you! 👍

**Comment by vgheo** [comment]
Same goes from my side. Thanks for the fix.
