### ISSUE TITLE
duplicate namespace added when renaming a concordion tag

### ISSUE THREAD

**Issue by drtimwright** [concordion/idea-concordion-support#6]
Hi there,

I often start my concordion tests with a concordion:echo command and later change it to a concordion:assertEquals command. The plugin is being great and autocompleting the assertEquals, but it it duplicating the namespace, so I end up with:

c:c:assertEquals (because I use "c" as the concordion namespace for brevity).

Tim

**Comment by drtimwright** [comment]
Sequential screen snapshots:

![logon-1](https://cloud.githubusercontent.com/assets/7540034/10872311/03083598-8164-11e5-98a8-dedee8e762b3.png)

![logon-2](https://cloud.githubusercontent.com/assets/7540034/10872313/060fb3ce-8164-11e5-9521-ea1e6b7cb0bf.png)

![logon-3](https://cloud.githubusercontent.com/assets/7540034/10872314/08b93898-8164-11e5-8208-9b7170d5f09e.png)

**Comment by gmandnepr** [comment]
Hello Tim,

Thanks for reporting this issue.
0.2 release is waiting for approval at jetbrains repository right now, so this will be part of 0.3 release, probably in week or two.
